export const AGENT_INFO = {
  name: 'Deepak Sharma',
  role: 'Real Estate Consultant',
  location: 'Noida & Yamuna Expressway',
  coverage: 'Noida | Greater Noida | Yamuna Expressway',
  services: 'Residential & Commercial Properties',
  servicesList: 'Buying • Selling • Renting',
  phone: '9953245542',
  displayPhone: '+91 99532 45542',
  whatsappNumber: '919953245542',
  tagline: 'Residential & Commercial Property Consultant',
  motto: '|| Self Believer ||',
};

export function getWhatsAppUrl(message: string): string {
  return `https://wa.me/${AGENT_INFO.whatsappNumber}?text=${encodeURIComponent(message.trim())}`;
}

export const PREFILLED_MESSAGES = {
  hero: 'Hi Deepak, I am looking for property assistance in Noida & Yamuna Expressway. Please share available options.',
  buying: 'Hi Deepak, I am looking to BUY a residential/commercial property in Noida/Yamuna Expressway. Please share suitable options.',
  selling: 'Hi Deepak, I want to SELL my property in Noida/Yamuna Expressway. Please assist me with genuine buyers.',
  renting: 'Hi Deepak, I am looking to RENT / RENT OUT a property in Noida/Yamuna Expressway. Please share details.',
  generalInquiry: 'Hi Deepak, I am looking for a property in Noida/Yamuna Expressway. I would like to discuss my requirement.',
  floating: 'Hi Deepak, I found your website and I am interested in a property in Noida/Yamuna Expressway. Please share available options.',
  propertyTypes: "Hi Deepak, I am looking for property options in Noida/Yamuna Expressway. Here is what I am looking for:",
};

export const RESIDENTIAL_TYPES = [
  { name: 'Apartments', desc: 'High-rise luxury & affordable apartments with modern amenities.' },
  { name: 'Flats', desc: 'Ready-to-move and under-construction 2, 3 & 4 BHK units.' },
  { name: 'Villas', desc: 'Independent luxury villas, duplexes, and gated community homes.' },
  { name: 'Plots', desc: 'Authority & freehold residential plots with clear titles.' },
];

export const COMMERCIAL_TYPES = [
  { name: 'Shops', desc: 'Retail high-street shops with high footfall & guaranteed rental yield.' },
  { name: 'Offices', desc: 'Lockable corporate office spaces & IT/ITES park workspaces.' },
  { name: 'Commercial Spaces', desc: 'Food courts, anchor stores, and institutional spaces.' },
  { name: 'Commercial Plots', desc: 'Commercial zoned land parcels for showrooms and warehouses.' },
];

export const FEATURED_PROPERTIES = [
  {
    id: 'prop-kothi-131',
    sequence: 1,
    title: 'Independent Kothi for Rent',
    type: 'rental',
    category: 'Residential Rental',
    tag: 'INDEPENDENT KOTHI',
    badge: 'EXCLUSIVE RENTAL',
    location: 'Sector 131, Jaypee Wish Town, Noida',
    specs: '6 BHK • 6 Washrooms • 3 Independent Floors',
    price: '₹ 1,50,000 / mo',
    priceSubtitle: '2 Months Deposit + 1 Month Advance • 3-5 Years Lease',
    beds: 6,
    baths: 6,
    floors: '3 Floors',
    sqft: '4,500 Sq. Ft.',
    furnishing: 'Fully Furnished (6 Beds, Wardrobes, Geysers, Fridge, Sofa, Dining, RO per floor)',
    image: 'https://i.ibb.co/BHddMhbv/IMG-20260920-WA0028.jpg',
    unoptimized: true,
    highlight: 'Suitable for Airbnb / Guest House / Corporate Stays / Family. Owner resides in Delhi.',
    features: [
      '6 Double Beds & 6 Wardrobes installed',
      '6 Geysers & 1 Washing Machine',
      'Per Floor: Sofa, Dining Table, Refrigerator, RO & Induction',
      '5 Dressing Mirrors per room & full curtains',
      '3 to 5 Years Long-term lease available',
      '15-day brokerage applicable from both sides (in 3 parts)',
    ],
    whatsappMessage:
      'Hi Deepak, I am interested in the Independent Kothi for rent in Sector 131 Jaypee Wish Town (6 BHK, 3 Floors, 1.5 Lakh/mo). Please share details and arrange a visit.',
  },
  {
    id: 'prop-comm-shops',
    sequence: 2,
    title: 'Commercial Shops & Retail Spaces for Rent',
    type: 'commercial',
    category: 'Commercial Leasing',
    tag: 'RETAIL SHOPS',
    badge: 'FOR LEASE',
    location: 'Botanical Garden, Sec 44-49, Phase 2, Bhangel, Noida',
    specs: '150 to 5,000+ Sq. Ft. Retail & SCO Units',
    price: '₹ 15,000 to ₹ 5,00,000+ / mo',
    priceSubtitle: 'Immediate Possession • High-Footfall Commercial Corridors',
    beds: null,
    baths: 1,
    floors: 'Ground / Upper Floors',
    sqft: '150 - 5,000+ Sq. Ft.',
    furnishing: 'Bare Shell / Semi-Fitted / Ready to Move',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    unoptimized: false,
    highlight: 'Ideal for pharmacies, grocery stores, cafes, salons, clinics, clothing outlets and showrooms.',
    features: [
      'Prime high-footfall main road locations',
      'Roadside booths, high-street market arcades & standalone shops',
      'Active sectors: Botanical Garden, Sec 44, 45, 46, 47, 48, 49, Phase 2, Bhangel',
      'Dedicated customer parking & heavy daily vehicular traffic',
      'Flexible lease tenures with favorable rent-free fitout period',
      'Direct assistance with lease deed registration & site inspections',
    ],
    whatsappMessage:
      'Hi Deepak, I am looking for Commercial Shops / Retail Spaces for Rent in Noida (Botanical Garden, Sec 44-49, Phase 2, Bhangel). Please share available options.',
  },
  {
    id: 'prop-golf-150',
    sequence: 3,
    title: 'Skyline Golf-Facing Luxury Residences',
    type: 'sale',
    category: 'Luxury Residential',
    tag: 'PENTHOUSE & FLATS',
    badge: 'FOR SALE',
    location: 'Sector 150, Noida Expressway',
    specs: '3 & 4 BHK Luxury Residences',
    price: '₹ 1.85 Cr onwards',
    priceSubtitle: 'Direct Developer / Resale • Ready & Near Completion Units',
    beds: 4,
    baths: 4,
    floors: 'Tower High-Rise',
    sqft: '2,850 Sq. Ft.',
    furnishing: 'Semi-Furnished Luxury Specification',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
    unoptimized: false,
    highlight: 'Unobstructed golf views, 80% open green acreage, direct access to Noida Expressway & Metro.',
    features: [
      'Overlooking 9-hole international golf course',
      'Sports City infrastructure with cricket academy & tennis courts',
      'Ultra-low density sector with eco-friendly master planning',
      'Exclusive clubhouse, Olympic-size pool & sports complex',
      '3-tier 24/7 security with biometric access',
      'Direct connectivity to upcoming Jewar International Airport',
    ],
    whatsappMessage:
      'Hi Deepak, I am interested in the Skyline Golf-Facing Residences in Sector 150 (3 & 4 BHK, 1.85 Cr). Please share available inventory and payment plan.',
  },
  {
    id: 'prop-apt-137',
    sequence: 4,
    title: 'Modern High-Rise Apartment in Sector 137',
    type: 'rental',
    category: 'Residential Rental',
    tag: 'APARTMENT',
    badge: 'FOR RENT',
    location: 'Sector 137, Noida Expressway',
    specs: '3 BHK Semi-Furnished Flat',
    price: '₹ 42,000 / mo',
    priceSubtitle: 'Maintenance Included • Ready to Move In',
    beds: 3,
    baths: 3,
    floors: 'Mid Floor View',
    sqft: '1,750 Sq. Ft.',
    furnishing: 'Semi-Furnished with Modular Kitchen & Wardrobes',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
    unoptimized: false,
    highlight: 'Walking distance to Aqua Line Metro, premium gated society with active club & pool.',
    features: [
      'Modular kitchen with chimney & pre-installed cabinets',
      'Built-in wooden wardrobes in all bedrooms',
      'Spacious balconies with airy open city views',
      '100% power backup & multi-level secure parking',
      'Gated society with clubhouse, gym, and swimming pool',
      'Immediate walking access to Metro Station & commercial shopping arcade',
    ],
    whatsappMessage:
      'Hi Deepak, I am looking to rent the 3 BHK Apartment in Sector 137 Noida Expressway (₹42,000/mo). Please share current status and arrange a visit.',
  },
  {
    id: 'prop-villa-pari',
    sequence: 5,
    title: 'Heritage Independent Luxury Villa',
    type: 'sale',
    category: 'Luxury Residential',
    tag: 'LUXURY BUNGALOW',
    badge: 'FOR SALE',
    location: 'Pari Chowk, Greater Noida',
    specs: '5 BHK Luxury Duplex Villa with Lawn',
    price: '₹ 3.85 Cr',
    priceSubtitle: 'Freehold Clear Title • Ready for Immediate Registry',
    beds: 5,
    baths: 5,
    floors: 'G + 2 Duplex',
    sqft: '4,600 Sq. Ft.',
    furnishing: 'Premium Semi-Furnished with Imported Marble',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    unoptimized: false,
    highlight: 'Private landscaped green lawn, Italian marble flooring, internal private elevator and terrace lounge.',
    features: [
      'Exclusive private lawn and landscaped boundary',
      'Italian Botticino marble & double-height grand entrance',
      'Private internal hydraulic elevator serving all 3 levels',
      'Separate servant room with attached washroom',
      '4 covered car parking spaces within private gate',
      'Prime location 2 minutes from Pari Chowk Metro Station',
    ],
    whatsappMessage:
      'Hi Deepak, I am interested in the 5 BHK Heritage Independent Luxury Villa at Pari Chowk (₹3.85 Cr). Please share title details and site visit slot.',
  },
  {
    id: 'prop-plot-yamuna',
    sequence: 6,
    title: 'Yamuna Expressway Authority Plots (YEIDA)',
    type: 'plot',
    category: 'Plots / Land',
    tag: 'AUTHORITY PLOT',
    badge: 'AUTHORITY REGISTERED',
    location: 'Sector 18 & 20, Yamuna Expressway',
    specs: '300 & 500 Sq. Mtr. Registered Plots',
    price: '₹ 1.25 Cr onwards',
    priceSubtitle: 'Clear Legal Titles • Registry Ready & Transfer Allowed',
    beds: null,
    baths: null,
    floors: 'Independent Construction (G+2 / G+3)',
    sqft: '3,230 - 5,380 Sq. Ft.',
    furnishing: 'Demarcated Land Parcel',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
    unoptimized: false,
    highlight: 'Directly positioned along the Jewar International Airport & Film City high-speed growth corridor.',
    features: [
      '100% YEIDA authorized with crystal clear title paperwork',
      'Wide 18m, 24m, and 45m sector approach roads with underground utilities',
      '5 minutes from upcoming Noida International Airport (Jewar)',
      'Adjacent to proposed International Film City & Olympic City hubs',
      'Fastest capital appreciation corridor in North India',
      'Complete legal verification and hassle-free authority transfer assistance',
    ],
    whatsappMessage:
      'Hi Deepak, I am interested in YEIDA Authority Plots in Sector 18 & 20 Yamuna Expressway (1.25 Cr onwards). Please share current availability and transfer procedure.',
  },
  {
    id: 'prop-comm-sale',
    sequence: 7,
    title: 'Prime High-Street Retail Shops & Lockable Offices',
    type: 'commercial',
    category: 'Commercial Investment',
    tag: 'COMMERCIAL ASSET',
    badge: 'HIGH-YIELD ASSET',
    location: 'Central Noida & Expressway Commercial Corridor',
    specs: 'Lockable Retail & Office Suites (650+ Sq. Ft.)',
    price: '₹ 55.0 Lakh onwards',
    priceSubtitle: 'Pre-Leased & Self-Use Units • High Rental Yield',
    beds: null,
    baths: 1,
    floors: 'Ground, 1st & Corporate Floors',
    sqft: '650+ Sq. Ft.',
    furnishing: 'Warm Shell / Fully Furnished Office Option',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    unoptimized: false,
    highlight: 'High footfall density, guaranteed lease assistance, top national brands neighbor, 8-10% rental returns.',
    features: [
      'Front-facing double-height retail storefronts with maximum signage visibility',
      'Surrounded by 50,000+ affluent residential families in immediate vicinity',
      'Lockable commercial office spaces with high-speed internet & HVAC',
      'Assisted tenant leasing to national and international brand franchises',
      'Low entry ticket size starting at ₹55 Lacs with easy construction-linked plans',
      'Grade-A corporate architecture with multi-level basement car parking',
    ],
    whatsappMessage:
      'Hi Deepak, I am looking to invest in Prime Commercial Retail / Office Spaces in Noida (starting ₹55 Lakh). Please share available inventory and projected ROI.',
  },
];

export const TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Priya Sharma',
    role: 'Homeowner in Sector 150',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    rating: 5,
    text: 'Deepak Sharma found us the perfect golf-facing apartment in Sector 150. His team was transparent, guided us through all registry paperwork seamlessly, and negotiated the best price. Highly recommended!',
  },
  {
    id: 'test-2',
    name: 'Rajeev Malhotra',
    role: 'Investor in Yamuna Expressway',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop',
    rating: 5,
    text: 'Genuine authority plot deal near Jewar Airport. Deepak provided 100% legal verification and clear paperwork within 3 days. Best property consultant in Noida!',
  },
  {
    id: 'test-3',
    name: 'Amit & Neha Verma',
    role: 'Villa Buyers in Greater Noida',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    rating: 5,
    text: 'Exceptional service! We were looking for an independent villa for 6 months. Deepak arranged immediate site visits and closed the deal below our expected budget.',
  },
];

export const WHY_CHOOSE_US = [
  {
    id: 'verified',
    title: '100% Verified Listings',
    desc: 'Every property goes through a rigorous physical inspection and legal check before making it to our recommendations.',
    icon: 'ShieldCheck',
  },
  {
    id: 'fast',
    title: 'Lightning Fast Process',
    desc: 'End-to-end documentation and direct consultant coordination speed up your buying or selling experience.',
    icon: 'Clock',
  },
  {
    id: 'insights',
    title: 'Deep Locality Insights',
    desc: 'Get data-driven insights about neighborhoods, connectivity, and Jewar Airport infrastructure developments.',
    icon: 'MapPin',
  },
  {
    id: 'price',
    title: 'Best Price Guarantee',
    desc: 'We negotiate directly with top developers and genuine owners to bring you exclusive offers and guaranteed lowest market prices.',
    icon: 'BadgePercent',
  },
  {
    id: 'support',
    title: '24/7 Priority Support',
    desc: 'Your dedicated property consultant is available round the clock to assist you with any queries or site visits.',
    icon: 'Headphones',
  },
];

export const KEY_HUBS = [
  {
    name: 'Noida City & Expressway',
    sectors: 'Sectors 62, 74-79, 128, 137, 143, 150',
    description: 'Premier residential high-rises, corporate tech parks, and thriving green sectors.',
  },
  {
    name: 'Greater Noida',
    sectors: 'Pari Chowk, Knowledge Park, Delta, Omega, Alpha',
    description: 'Wide planned avenues, educational hubs, and spacious independent housing societies.',
  },
  {
    name: 'Yamuna Expressway',
    sectors: 'Sector 18, 20, 22D, Jewar International Airport corridor',
    description: 'India’s fastest appreciating investment zone with Film City, Formula 1 track, and airport.',
  },
];
